module.exports.author = [
    'James',
    'Robert',
    'John',
    'Michael',
    'David',
    'William',
    'William',
    'William',
    'Will',
    'Will',
    'Will',
    'Richard',
    'Joseph',
    'Thomas',
    'Charles',
    'Christopher',
    'Daniel',
    'Matthew',
    'Anthony',
    'Mark',
    'Donald',
    'Steven',
    'Paul',
    'Andrew',
    'Joshua',
    'Kenneth',
    'Kevin',
    'Brian',
    'George',
    'Timothy',
    'Ronald',
    'Edward',
    'Jason',
    'Jeffrey',
    'Ryan',
    'Mary',
    'Patricia',
    'Jennifer',
    'Linda',
    'Elizabeth',
    'Barbara',
    'Susan',
    'Jessica',
    'Sarah',
    'Karen',
    'Lisa',
    'Nancy',
    'Betty',
    'Margaret',
    'Sandra',
    'Ashley',
    'Kimberly',
    'Emily',
    'Donna',
    'Michelle',
    'Carol',
    'Amanda',
    'Dorothy',
    'Melissa',
    'Debra',
    'Stephanie',
    'Rebecca',
    'Sharon',
    'Laura',
    'Cynthia',
];

// Stars
module.exports.rating = [1, 2, 3, 4, 5];

//Review Text
module.exports.review = [
    'Pretty shaded and so very muddy even after days since rain. Wear appropriate shoes.',
    'Great hike. Not too crowded.',
    'Lots of steps!',
    "It's a great trail for a good work out.",
    'Super Crowded on a Saturday morning.',
    'Well maintained. Great up and downs.',
    'Very peaceful walk.',
    'Very well maintained especially considering all the rain. The grounds staff are to be commended for the great upkeep and care.',
    'Lots of up and down, good shade.',
    'Great two hour hike this morning! 85% was in the shade. Highly recommend and will do this hike again.',
    'There was lots of up and down, which I love. (If you have bad knees bring your hiking sticks for support.... you will thank me! )',
    'cool trails',
    'Muddy!',
    'Easy trail, lots of bikers. ',
    'Very popular trail for bikers, so definitely keep an eye/ear out for them. Great trail with some nice views!',
    'Great training day for big trip in November. ',
    "If it's even a little wet, use caution.",
    'Way too crowded.',
    'Boring!',
    'overrated',
    'basic. really a bike trail.',
    'mixed prairie and woodland. some lake views',
    'closed today',
    'Humid but great',
    'It was a good mix of woods, flat parts, & some steep hills.',
    'mud',
    'Nicely marked great hike with my dog',
    'It was a little bit damp from the last rain but not enough to slip or get the shoes dirty ',
    'It was too muddy(from the rain) to do all the loops.',
    'Great scenery for the most part, a it weird that is right next to some apartments which you can see during your hike. ',
    'Overall, fun hike!',
    'Good unpaved trail in the woods, shared with bikes, but not a problem.',
    'great trail ! loved it',
    'An incredible amount of rubbish on the trail, in the waterways and trees....so sad to see.',
    'Nice short 20 min walk. Too much trash though. ',
    'Trail is okay. But there was a lot of trash.',
    'Confusing/ lacking signage',
    'Great',
    'Nice paved walking trail that is well kept. Very peaceful on a Tuesday Morning.',
    'The loop on the map was overgrown but we found an alternate trail that led us back onto a paved portion of the loop back to the beginning.',
    'the trail was very well maintained and was a very easy walk!',
    'A little short but nice.',
    'not a fan. ',
    'well shaded, paved and unpaved however I skipped parts of the unpaved trail due to overgrowth and an abundance of poison ivy.',
    "so much trash in the creek, it's next to apartments and there's moderate traffic noise the whole time. ",
    'skip it. ',
    'Paved trail is super easy.',
    'Beginner and kid friendly.',
    'Wonderful afternoon',
    'Nice out and back trail. Well marked',
    'Nice trail mostly cement.',
    'my first time ever doing this. i liked it. would do it again.',
    'Nice trail for leisurely stroll',
    'My favorite part of the trail was the part that was not paved.',
    'Could really do with a few signposts.',
    'Beautiful oasis',
    'Very nature trail, feels more open and has a ranch kind of vibe',
    'Lovely paved walk through the woods. You can short cut it back to the car if you go under then over the bridge. ',
    'This is definitely a hidden gem. ',
    'Pretty sad! ',
    'clean, easy nice trail ',
    'clean, difficult fun trail ',
    'Nice trail. Very scenic. Paved and sand.',
    'Expected more wooded trails, oh well off to the next one. ',
    'Shady trail. Lots of dead ends. Pretty.',
    "TBH this wasn't really a very interesting trail. ",
    "It's highly shaded which is nice but not really for riding your bike.",
    'Too many people with speakers',
    'Great family trail.',
    'Great trail hidden away!',
    'More of a leisurely walk than a hike. ',
    "The 1850's Homestead site was really neat to see. ",
    'Kid friendly. Nice brisk walk. ',
    'Wow that hike killed my legs!',
    'This is much harder than expected',
    ':)',
    'Difficulty is wrong',
];
