module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Gloomy',
    'Silent',
    'Redwood',
    'Shady',
    'Golden',
    'Misty',
    'Little',
    'Bear',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Frosty',
    'Wandering',
    'Bronze',
    'Steel',
    'Fort',
    'Brown',
    'Great',
    'Pacific',
    'Appalachian',
    'Old',
    'New',
    'North',
    'South',
    'East',
    'West',
    'High',
    'Low',
];

module.exports.places = [
    'Flats',
    'Springs',
    'Valley',
    'Canyon',
    'Pond',
    'Dunes',
    'Ghost Town',
    'View',
    'Landing',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Bayshore',
    'Sands',
    'Forest',
    'Cliffs',
    'Hollow',
    'Marsh',
    'Falls',
    'Lake',
    'Mine',
    'Walk',
    'Crest',
    'Pioneer',
    'England',
    'Divide',
    'Age',
];

module.exports.difficulty = [
    'Very Easy',
    'Easy',
    'Medium',
    'Hard',
    'Very Hard',
    'Dangerous',
];

module.exports.descriptions = [
    'This trail leads to rewarding views from the north or south rim of the Valley, but water can be limited in late summer. This region is the most popular, and most crowded, portion of the park.',
    'This trail requires backpackers to hike at least four miles before camping. This mountainous high country has an abundance of peaks, lakes, creeks, rivers, and waterfalls, but temperatures will be significantly cooler than elsewhere in the park. This region is very popular with backpackers during summer, and is correspondingly busy.',
    'At the southern end of the park, Wawona is a quiet, forested area with trails that lead to waterfalls, lakes, and stunning granite features. In late summer, trails become hot and dry.',
    'The immediate area around the reservoir is a no-camping zone, but hiking over six miles will lead to wonderful cascade waterfalls or peaceful lakes. This trail tends to be busiest in the spring and fall because of its low-elevation destinations and warm temperatures. In the summer, it can be very arid and hot.',
    'A short hike leads to a quaint little picnic area. Paved and easy for families.',
    "As you walk along this trail, take a moment and listen. You're guaranteed to hear songs and calls from different species of birds. At sunrise and sunset, listen for the call of owls. In the spring and fall, watch for migratory birds from Alaska, Mexico and Canada, who rest here before continuing their journey. On the national park's waterfront, keep an eye out for different waterfowl, gull, shorebird, and grebe species.",
    'Hike through a forest dominated by maple, beech, basswood and oak trees. Follow a stretch of the Little River and explore the recently restored Prairie. Explore the historic Homestead and Farm.',
    'This hike highlights an area of such outstanding plant diversity that it was designated as a National Natural Landmark. Explore several distinct habitats including ponds, marshes, swamps, black oak savannas and beaches.',
    'This short hike on a paved trail features the ridge, which was a shoreline over 12,000 years ago. ',
    "This trails tell a story. You may learn about natural processes in the park, the plants and animals, how our ancestors lived in the area, or all three! This trail is short and accessible to wheelchairs. While you're on the trail, you'll find signs on the path that share more information about the world around you.",
    'Hikers, bicyclists, and horses share the dirt on this multi-use trail. Know your right of way! Be mindful of trail etiquette on multi-use trails. Bikes and horses can use some trails and roads, but be sure to check for signs. Check with the park to find designated bike trails.',
    'This is a quiet, forested area with trails that lead to waterfalls, lakes, and stunning granite features. In late summer, trails become hot and dry.',
    "Don't count on staying dry when you hike this behemoth! After a rough road to the trailhead, you'll face a creek crossing that can be difficult or even dangerous during the season's peak runoff period. Just remember to come prepared.",
    'Cross country ski trails in winter, hiking and mountain bike trails in summer; This trail offers miles of easy hiking trails. These trails, at old logging roads, wind their way through a picturesque forest landscape with lots of gentle ups and downs to keep the outing visually interesting and lots of fun.',
    'This trail accesses beautiful  and its alpine surroundings. The trail climbs to local plateaus for fantastic views of the bay. Look for bears and mountain goats on the high ridges.',
];

module.exports.imageURLs = [
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684016/TrailPages/Seed%20Images/toomas-tartes-Yizrl9N_eDA-unsplash_dnz44s.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684016/TrailPages/Seed%20Images/ashley-knedler-Pf5Pj7A5ddA-unsplash_fzpo61.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684016/TrailPages/Seed%20Images/jake-melara-Yh6K2eTr_FY-unsplash_e3vpbq.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684015/TrailPages/Seed%20Images/photo-nic-xOigCUcFdA8-unsplash_ptuiuk.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684340/TrailPages/Seed%20Images/wojciech-then-DijA5f0voGQ-unsplash_m2rcrg.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684340/TrailPages/Seed%20Images/tobias-mrzyk-iuqmGmst5Po-unsplash_h17apo.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684340/TrailPages/Seed%20Images/y-s-cpPTw3b8paM-unsplash_tb78wu.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684340/TrailPages/Seed%20Images/timmy-wesley-3Ltn2aWVNcM-unsplash_ntnqsu.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684341/TrailPages/Seed%20Images/tim-foster-lSegRSDBMLw-unsplash_nzofap.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684341/TrailPages/Seed%20Images/ophelie-authier-X0SMdQSQwzc-unsplash_rl0qbc.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684341/TrailPages/Seed%20Images/wu-jianxiong-UniC8xhlzaE-unsplash_bird5o.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684342/TrailPages/Seed%20Images/nathan-dumlao-pLoMDKtl-JY-unsplash_y8k8lv.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684342/TrailPages/Seed%20Images/nina-luong-dy4QG5c5xWQ-unsplash_zshzp4.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684343/TrailPages/Seed%20Images/kristjan-kotar--h15p84GY5k-unsplash_hrldzf.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684343/TrailPages/Seed%20Images/mariah-krafft-g87PtqNlqOE-unsplash_eb6nmn.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684342/TrailPages/Seed%20Images/stephen-leonardi-4KciTa1RB80-unsplash_cpzof1.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684343/TrailPages/Seed%20Images/nasim-dadfar-w28Ei0Ap96w-unsplash_uti6cz.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684345/TrailPages/Seed%20Images/joshua-earle-C6duwascOEA-unsplash_hchoo9.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684345/TrailPages/Seed%20Images/juliane-liebermann-Pw7i-YVg5uM-unsplash_f4hoha.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684345/TrailPages/Seed%20Images/jon-flobrant-_r19nfvS3wY-unsplash_bgva0n.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684345/TrailPages/Seed%20Images/kalen-emsley-7bwQXzbF6KE-unsplash_d7cbbl.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684345/TrailPages/Seed%20Images/joanna-nix-walkup-Osq7UAVxIOI-unsplash_kbue6j.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684345/TrailPages/Seed%20Images/krisjanis-mezulis-__E07WwlywA-unsplash_i5l45h.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684346/TrailPages/Seed%20Images/fabrizio-conti-xPFhK0MGsyw-unsplash_fg6lpg.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684347/TrailPages/Seed%20Images/holly-mandarich-Y90GKsTKxBM-unsplash_vf8jlb.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684349/TrailPages/Seed%20Images/andreas-wagner-8H5kNkYmJYQ-unsplash_asujrl.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684349/TrailPages/Seed%20Images/anastasia-petrova-xu2WYJek5AI-unsplash_evfbar.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684349/TrailPages/Seed%20Images/anastasia-petrova-xu2WYJek5AI-unsplash_evfbar.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684348/TrailPages/Seed%20Images/brad-barmore-IQxcuHBF7Uo-unsplash_l6lli2.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684348/TrailPages/Seed%20Images/carlos-0yuIA1K7LyA-unsplash_d5s99d.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684348/TrailPages/Seed%20Images/david-gavi-Ijx8OxvKrgM-unsplash_i2dxgn.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684348/TrailPages/Seed%20Images/holly-mandarich-bMog4gpujsI-unsplash_t61edy.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684347/TrailPages/Seed%20Images/colby-winfield-hHdJNsiCzfI-unsplash_altm4s.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660684347/TrailPages/Seed%20Images/clemence-bergougnoux-zLIrNgNzPYs-unsplash_golfnd.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686207/TrailPages/Seed%20Images/taylor-simpson-vCxw1JjjhXw-unsplash_dwep20.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686207/TrailPages/Seed%20Images/tim-foster-26oLqDwFW44-unsplash_iopus5.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686208/TrailPages/Seed%20Images/taylor-simpson-cxRsiXQcWKU-unsplash_pm5rcp.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686212/TrailPages/Seed%20Images/kevin-johnston-wL6Z5fYAVfA-unsplash_ftxcr7.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686211/TrailPages/Seed%20Images/lane-jackman-RhnfW97145w-unsplash_bkqtv9.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686211/TrailPages/Seed%20Images/matijn-palings-faNXOVGDKHk-unsplash_gac9kn.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686210/TrailPages/Seed%20Images/omer-salom-LoijtQXXNhs-unsplash_tykupc.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686210/TrailPages/Seed%20Images/leslie-cross-QhdV5fOLKp4-unsplash_ymrlys.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686210/TrailPages/Seed%20Images/sandro-gonzalez-bQBrzZEqjVs-unsplash_j8ueqw.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686209/TrailPages/Seed%20Images/rayne-leach-7fBgq2tCliA-unsplash_rnocl6.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686208/TrailPages/Seed%20Images/simon-english-dYcypsY4i3I-unsplash_arhfgu.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686208/TrailPages/Seed%20Images/rohit-d-silva-WhAI_vc0r7Y-unsplash_eqaasc.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686211/TrailPages/Seed%20Images/laura-kennedy-XRf3KYdyCQ8-unsplash_efadim.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686211/TrailPages/Seed%20Images/laura-baker-LmDLsHT4Mo0-unsplash_tiqcxk.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686212/TrailPages/Seed%20Images/kristin-snippe-6NwrVDNsTx4-unsplash_jod2h1.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686212/TrailPages/Seed%20Images/joshua-j-cotten-JMR0nilVEBA-unsplash_lcyigk.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686213/TrailPages/Seed%20Images/jonathan-fox-0LXFLzDOfuA-unsplash_d9u1cn.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686213/TrailPages/Seed%20Images/jeremy-alford-QnugMBWVdAI-unsplash_usu5vs.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686214/TrailPages/Seed%20Images/joshua-gresham-bB759zj7yvs-unsplash_gvdv4o.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686214/TrailPages/Seed%20Images/kevin-johnston-IkXk9pGZ44A-unsplash_uoorxd.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686214/TrailPages/Seed%20Images/jeff-golenski-aCzud3scCbM-unsplash_gdfpij.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686217/TrailPages/Seed%20Images/eddie-suh-jC-uNQyP-Gc-unsplash_a1uevj.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686217/TrailPages/Seed%20Images/andreas-dress-moEMhjJwlrs-unsplash_j6pycb.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686217/TrailPages/Seed%20Images/haitham-7YAsaTuOmo0-unsplash_qzy2qs.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686217/TrailPages/Seed%20Images/adrian-n-wpMw3wIuNfI-unsplash_kulgo4.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686216/TrailPages/Seed%20Images/haitham-EtOXQSpWjEU-unsplash_my4inv.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686215/TrailPages/Seed%20Images/jake-melara-Yh6K2eTr_FY-unsplash_th9mnc.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686215/TrailPages/Seed%20Images/haitham-heJZ9hHcp-c-unsplash_n96uki.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686214/TrailPages/Seed%20Images/jeremiah-lawrence-hV7thVmVZ4E-unsplash_h0ed1j.jpg',
    'https://res.cloudinary.com/djigjf2ob/image/upload/v1660686215/TrailPages/Seed%20Images/harry-gillen-C2waufpOUwA-unsplash_ivrcoe.jpg',
];
